name: Deploy static to S3

on:
  push:
  pull_request:
    types: [opened]

env:
  TELEGRAM_GROUP_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  TELEGRAM_TOPIC_ID: ${{ secrets.TELEGRAM_TOPIC_ID }}
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-static:
    name: Deploy static to s3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Deploy static folder to S3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --no-verify-ssl
        env:
          AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ru-7"
          SOURCE_DIR: "static"
          DEST_DIR: "static"

  notify_success:
    name: Success Message
    runs-on: ubuntu-latest
    needs: deploy-static
    steps:
      - name: Send Telegram Success Message
        uses: PacificPromise/macos-telegram-action@main
        with:
          type: topic
          message: |
            ✅ Изменения статики успешно задеплоены

  notify_failure:
    name: Failure Message
    if: ${{ needs.deploy-static.result == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Failure Message
        uses: PacificPromise/macos-telegram-action@main
        with:
          type: topic
          message: |
            ❗️ Произошла ошибка во время деплоя статики
